package com.example.scotlandyard.moving;

import com.example.scotlandyard.map.Route;
import com.example.scotlandyard.map.Routes;
import com.example.scotlandyard.map.ValidatedRoute;

import org.junit.After;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.junit.runners.Parameterized;

import java.util.Arrays;

import static com.example.scotlandyard.map.routetypes.BicycleRoutes.getBicycle;
import static com.example.scotlandyard.map.routetypes.BusRoutes.getBUS;
import static com.example.scotlandyard.map.routetypes.FootRoutes.getByFoot;
import static com.example.scotlandyard.map.routetypes.TaxiRoutes.getTaxiDragan;

@RunWith(Parameterized.class)
public class RoutesTest {

    private static final Route[] BY_FOOT = getByFoot();
    private static final Route[] BICYCLE = getBicycle();
    private static final Route[] BUS = getBUS();
    private static final Route[] TAXI_DRAGAN = getTaxiDragan();

    @Parameterized.Parameters(name = "{index}: Route from {0} to {1} is type {2}, valid - {3}")
    public static Iterable data() {
        return Arrays.asList(new Object[][]{
                /* Foot */
                {1, 2, 0, true, Routes.getByFootRoutes()[0]},
                {2, 3, 0, true, Routes.getByFootRoutes()[1]},
                {2, 4, 0, true, Routes.getByFootRoutes()[2]},
                {3, 5, 0, true, Routes.getByFootRoutes()[3]},
                {4, 6, 0, true, Routes.getByFootRoutes()[4]},
                {5, 6, 0, true, Routes.getByFootRoutes()[5]},
                {6, 7, 0, true, Routes.getByFootRoutes()[6]},
                {7, 8, 0, true, Routes.getByFootRoutes()[7]},
                {8, 9, 0, true, Routes.getByFootRoutes()[8]},
                {9, 10, 0, true, Routes.getByFootRoutes()[9]},
                {10, 11, 0, true, Routes.getByFootRoutes()[10]},
                {10, 18, 0, true, Routes.getByFootRoutes()[11]},
                {10, 38, 0, true, Routes.getByFootRoutes()[12]},
                {12, 13, 0, true, Routes.getByFootRoutes()[13]},
                {13, 14, 0, true, Routes.getByFootRoutes()[14]},
                {14, 15, 0, true, Routes.getByFootRoutes()[15]},
                {16, 17, 0, true, Routes.getByFootRoutes()[16]},
                {17, 24, 0, true, Routes.getByFootRoutes()[17]},
                {19, 20, 0, true, Routes.getByFootRoutes()[18]},
                {20, 21, 0, true, Routes.getByFootRoutes()[19]},
                {21, 24, 0, true, Routes.getByFootRoutes()[20]},
                {21, 23, 0, true, Routes.getByFootRoutes()[21]},
                {21, 22, 0, true, Routes.getByFootRoutes()[22]},
                {22, 23, 0, true, Routes.getByFootRoutes()[23]},
                {22, 25, 0, true, Routes.getByFootRoutes()[24]},
                {23, 24, 0, true, Routes.getByFootRoutes()[25]},
                {24, 27, 0, true, Routes.getByFootRoutes()[26]},
                {24, 26, 0, true, Routes.getByFootRoutes()[27]},
                {25, 26, 0, true, Routes.getByFootRoutes()[28]},
                {26, 27, 0, true, Routes.getByFootRoutes()[29]},
                {28, 38, 0, true, Routes.getByFootRoutes()[30]},
                {28, 35, 0, true, Routes.getByFootRoutes()[31]},
                {28, 29, 0, true, Routes.getByFootRoutes()[32]},
                {28, 39, 0, true, Routes.getByFootRoutes()[33]},
                {29, 36, 0, true, Routes.getByFootRoutes()[34]},
                {29, 35, 0, true, Routes.getByFootRoutes()[35]},
                {29, 45, 0, true, Routes.getByFootRoutes()[36]},
                {30, 37, 0, true, Routes.getByFootRoutes()[37]},
                {30, 53, 0, true, Routes.getByFootRoutes()[38]},
                {30, 60, 0, true, Routes.getByFootRoutes()[39]},
                {31, 66, 0, true, Routes.getByFootRoutes()[40]},
                {32, 66, 0, true, Routes.getByFootRoutes()[41]},
                {33, 36, 0, true, Routes.getByFootRoutes()[42]},
                {33, 37, 0, true, Routes.getByFootRoutes()[43]},
                {34, 35, 0, true, Routes.getByFootRoutes()[44]},
                {36, 37, 0, true, Routes.getByFootRoutes()[45]},
                {38, 39, 0, true, Routes.getByFootRoutes()[46]},
                {40, 41, 0, true, Routes.getByFootRoutes()[47]},
                {41, 48, 0, true, Routes.getByFootRoutes()[48]},
                {42, 49, 0, true, Routes.getByFootRoutes()[49]},
                {42, 50, 0, true, Routes.getByFootRoutes()[50]},
                {42, 51, 0, true, Routes.getByFootRoutes()[51]},
                {43, 52, 0, true, Routes.getByFootRoutes()[52]},
                {43, 44, 0, true, Routes.getByFootRoutes()[53]},
                {43, 51, 0, true, Routes.getByFootRoutes()[54]},
                {45, 46, 0, true, Routes.getByFootRoutes()[55]},
                {46, 47, 0, true, Routes.getByFootRoutes()[56]},
                {46, 53, 0, true, Routes.getByFootRoutes()[57]},
                {47, 48, 0, true, Routes.getByFootRoutes()[58]},
                {47, 54, 0, true, Routes.getByFootRoutes()[59]},
                {48, 49, 0, true, Routes.getByFootRoutes()[60]},
                {50, 51, 0, true, Routes.getByFootRoutes()[61]},
                {51, 52, 0, true, Routes.getByFootRoutes()[62]},
                {52, 58, 0, true, Routes.getByFootRoutes()[63]},
                {53, 61, 0, true, Routes.getByFootRoutes()[64]},
                {54, 55, 0, true, Routes.getByFootRoutes()[65]},
                {55, 61, 0, true, Routes.getByFootRoutes()[66]},
                {55, 56, 0, true, Routes.getByFootRoutes()[67]},
                {56, 62, 0, true, Routes.getByFootRoutes()[68]},
                {56, 63, 0, true, Routes.getByFootRoutes()[69]},
                {56, 75, 0, true, Routes.getByFootRoutes()[70]},
                {57, 64, 0, true, Routes.getByFootRoutes()[71]},
                {57, 75, 0, true, Routes.getByFootRoutes()[72]},
                {57, 58, 0, true, Routes.getByFootRoutes()[73]},
                {58, 59, 0, true, Routes.getByFootRoutes()[74]},
                {59, 73, 0, true, Routes.getByFootRoutes()[75]},
                {60, 61, 0, true, Routes.getByFootRoutes()[76]},
                {60, 66, 0, true, Routes.getByFootRoutes()[77]},
                {66, 67, 0, true, Routes.getByFootRoutes()[78]},
                {62, 63, 0, true, Routes.getByFootRoutes()[79]},
                {63, 64, 0, true, Routes.getByFootRoutes()[80]},
                {63, 68, 0, true, Routes.getByFootRoutes()[81]},
                {64, 65, 0, true, Routes.getByFootRoutes()[82]},
                {65, 69, 0, true, Routes.getByFootRoutes()[83]},
                {65, 72, 0, true, Routes.getByFootRoutes()[84]},
                {68, 67, 0, true, Routes.getByFootRoutes()[85]},
                {68, 69, 0, true, Routes.getByFootRoutes()[86]},
                {69, 71, 0, true, Routes.getByFootRoutes()[87]},
                {70, 71, 0, true, Routes.getByFootRoutes()[88]},
                {71, 72, 0, true, Routes.getByFootRoutes()[89]},
                {71, 74, 0, true, Routes.getByFootRoutes()[90]},
                {72, 74, 0, true, Routes.getByFootRoutes()[91]},
                {72, 73, 0, true, Routes.getByFootRoutes()[92]},
                /* Bicycle */
                {1, 4, 1, true, Routes.getBicycleRoutes()[0]},
                {4, 19, 1, true, Routes.getBicycleRoutes()[1]},
                {6, 44, 1, true, Routes.getBicycleRoutes()[2]},
                {19, 21, 1, true, Routes.getBicycleRoutes()[3]},
                {17, 21, 1, true, Routes.getBicycleRoutes()[4]},
                {17, 20, 1, true, Routes.getBicycleRoutes()[5]},
                {15, 17, 1, true, Routes.getBicycleRoutes()[6]},
                {15, 16, 1, true, Routes.getBicycleRoutes()[7]},
                {17, 18, 1, true, Routes.getBicycleRoutes()[8]},
                {14, 18, 1, true, Routes.getBicycleRoutes()[9]},
                {11, 28, 1, true, Routes.getBicycleRoutes()[10]},
                {28, 34, 1, true, Routes.getBicycleRoutes()[11]},
                {33, 34, 1, true, Routes.getBicycleRoutes()[12]},
                {29, 30, 1, true, Routes.getBicycleRoutes()[13]},
                {30, 31, 1, true, Routes.getBicycleRoutes()[14]},
                {31, 32, 1, true, Routes.getBicycleRoutes()[15]},
                {31, 33, 1, true, Routes.getBicycleRoutes()[16]},
                {32, 67, 1, true, Routes.getBicycleRoutes()[17]},
                {32, 70, 1, true, Routes.getBicycleRoutes()[18]},
                {67, 70, 1, true, Routes.getBicycleRoutes()[19]},
                {61, 63, 1, true, Routes.getBicycleRoutes()[20]},
                {58, 65, 1, true, Routes.getBicycleRoutes()[21]},
                {59, 65, 1, true, Routes.getBicycleRoutes()[22]},
                {70, 74, 1, true, Routes.getBicycleRoutes()[23]},
                {73, 74, 1, true, Routes.getBicycleRoutes()[24]},
                {43, 58, 1, true, Routes.getBicycleRoutes()[25]},
                {43, 59, 1, true, Routes.getBicycleRoutes()[26]},
                {51, 58, 1, true, Routes.getBicycleRoutes()[27]},
                {50, 54, 1, true, Routes.getBicycleRoutes()[28]},
                {42, 43, 1, true, Routes.getBicycleRoutes()[29]},
                {40, 42, 1, true, Routes.getBicycleRoutes()[30]},
                {39, 40, 1, true, Routes.getBicycleRoutes()[31]},
                {40, 39, 1, true, Routes.getBicycleRoutes()[31]},
                /* Bus */
                {4, 16, 2, true, Routes.getBusRoutes()[0]},
                {12, 16, 2, true, Routes.getBusRoutes()[1]},
                {11, 12, 2, true, Routes.getBusRoutes()[2]},
                {11, 46, 2, true, Routes.getBusRoutes()[3]},
                {11, 41, 2, true, Routes.getBusRoutes()[4]},
                {41, 46, 2, true, Routes.getBusRoutes()[5]},
                {31, 46, 2, true, Routes.getBusRoutes()[6]},
                {4, 59, 2, true, Routes.getBusRoutes()[7]},
                {59, 74, 2, true, Routes.getBusRoutes()[8]},
                {41, 59, 2, true, Routes.getBusRoutes()[9]},
                {4, 41, 2, true, Routes.getBusRoutes()[10]},
                {41, 4, 2, true, Routes.getBusRoutes()[10]},
                /* Taxi */
                {10, 40, 3, true, Routes.getTaxiDraganRoutes()[0]},
                {32, 43, 3, true, Routes.getTaxiDraganRoutes()[1]},
                {12, 32, 3, true, Routes.getTaxiDraganRoutes()[2]},
                {12, 34, 3, true, Routes.getTaxiDraganRoutes()[3]},
                {34, 12, 3, true, Routes.getTaxiDraganRoutes()[3]},
                /* some invalid routes */
                /* 1 - 2 & 4 */
                {1, 3, -1, false, null},
                {1, 5, -1, false, null},
                {1, 6, -1, false, null},
                {1, 7, -1, false, null},
                {1, 8, -1, false, null},
                {1, 9, -1, false, null},
                {1, 10, -1, false, null},
                {1, 11, -1, false, null},
                {1, 12, -1, false, null},
                {1, 13, -1, false, null},
                {1, 14, -1, false, null},
                {1, 15, -1, false, null},
                {1, 16, -1, false, null},
                {1, 17, -1, false, null},
                {1, 18, -1, false, null},
                {1, 19, -1, false, null},
                {1, 20, -1, false, null},
                {1, 21, -1, false, null},
                {1, 22, -1, false, null},
                {1, 23, -1, false, null},
                {1, 24, -1, false, null},
                {1, 25, -1, false, null},
                {1, 26, -1, false, null},
                {1, 27, -1, false, null},
                {1, 28, -1, false, null},
                {1, 29, -1, false, null},
                {1, 30, -1, false, null},
                {1, 31, -1, false, null},
                {1, 32, -1, false, null},
                {1, 33, -1, false, null},
                {1, 34, -1, false, null},
                {1, 35, -1, false, null},
                {1, 36, -1, false, null},
                {1, 37, -1, false, null},
                {1, 38, -1, false, null},
                {1, 39, -1, false, null},
                {1, 40, -1, false, null},
                {1, 41, -1, false, null},
                {1, 42, -1, false, null},
                {1, 43, -1, false, null},
                {1, 44, -1, false, null},
                {1, 45, -1, false, null},
                {1, 46, -1, false, null},
                {1, 47, -1, false, null},
                {1, 48, -1, false, null},
                {1, 49, -1, false, null},
                {1, 50, -1, false, null},
                {1, 51, -1, false, null},
                {1, 52, -1, false, null},
                {1, 53, -1, false, null},
                {1, 54, -1, false, null},
                {1, 55, -1, false, null},
                {1, 56, -1, false, null},
                {1, 57, -1, false, null},
                {1, 58, -1, false, null},
                {1, 59, -1, false, null},
                {1, 60, -1, false, null},
                {1, 61, -1, false, null},
                {1, 62, -1, false, null},
                {1, 63, -1, false, null},
                {1, 64, -1, false, null},
                {1, 65, -1, false, null},
                {1, 66, -1, false, null},
                {1, 67, -1, false, null},
                {1, 68, -1, false, null},
                {1, 69, -1, false, null},
                {1, 70, -1, false, null},
                {1, 71, -1, false, null},
                {1, 72, -1, false, null},
                {1, 73, -1, false, null},
                {1, 74, -1, false, null},
                {1, 75, -1, false, null},

                /*2 - 1,2,4*/
                {2, 5, -1, false, null},
                {2, 6, -1, false, null},
                {2, 7, -1, false, null},
                {2, 8, -1, false, null},
                {2, 9, -1, false, null},
                {2, 10, -1, false, null},
                {2, 11, -1, false, null},
                {2, 12, -1, false, null},
                {2, 13, -1, false, null},
                {2, 14, -1, false, null},
                {2, 15, -1, false, null},
                {2, 16, -1, false, null},
                {2, 17, -1, false, null},
                {2, 18, -1, false, null},
                {2, 19, -1, false, null},
                {2, 20, -1, false, null},
                {2, 21, -1, false, null},
                {2, 22, -1, false, null},
                {2, 23, -1, false, null},
                {2, 24, -1, false, null},
                {2, 25, -1, false, null},
                {2, 26, -1, false, null},
                {2, 27, -1, false, null},
                {2, 28, -1, false, null},
                {2, 29, -1, false, null},
                {2, 30, -1, false, null},
                {2, 31, -1, false, null},
                {2, 32, -1, false, null},
                {2, 33, -1, false, null},
                {2, 34, -1, false, null},
                {2, 35, -1, false, null},
                {2, 36, -1, false, null},
                {2, 37, -1, false, null},
                {2, 38, -1, false, null},
                {2, 39, -1, false, null},
                {2, 40, -1, false, null},
                {2, 41, -1, false, null},
                {2, 42, -1, false, null},
                {2, 43, -1, false, null},
                {2, 44, -1, false, null},
                {2, 45, -1, false, null},
                {2, 46, -1, false, null},
                {2, 47, -1, false, null},
                {2, 48, -1, false, null},
                {2, 49, -1, false, null},
                {2, 50, -1, false, null},
                {2, 51, -1, false, null},
                {2, 52, -1, false, null},
                {2, 53, -1, false, null},
                {2, 54, -1, false, null},
                {2, 55, -1, false, null},
                {2, 56, -1, false, null},
                {2, 57, -1, false, null},
                {2, 58, -1, false, null},
                {2, 59, -1, false, null},
                {2, 60, -1, false, null},
                {2, 61, -1, false, null},
                {2, 62, -1, false, null},
                {2, 63, -1, false, null},
                {2, 64, -1, false, null},
                {2, 65, -1, false, null},
                {2, 66, -1, false, null},
                {2, 67, -1, false, null},
                {2, 68, -1, false, null},
                {2, 69, -1, false, null},
                {2, 70, -1, false, null},
                {2, 71, -1, false, null},
                {2, 72, -1, false, null},
                {2, 73, -1, false, null},
                {2, 74, -1, false, null},
                {2, 75, -1, false, null},

                /*3 - 2,5*/
                {3, 1, -1, false, null},
                {3, 3, -1, false, null},
                {3, 4, -1, false, null},
                {3, 6, -1, false, null},
                {3, 7, -1, false, null},
                {3, 8, -1, false, null},
                {3, 9, -1, false, null},
                {3, 10, -1, false, null},
                {3, 11, -1, false, null},
                {3, 12, -1, false, null},
                {3, 13, -1, false, null},
                {3, 14, -1, false, null},
                {3, 15, -1, false, null},
                {3, 16, -1, false, null},
                {3, 17, -1, false, null},
                {3, 18, -1, false, null},
                {3, 19, -1, false, null},
                {3, 20, -1, false, null},
                {3, 21, -1, false, null},
                {3, 22, -1, false, null},
                {3, 23, -1, false, null},
                {3, 24, -1, false, null},
                {3, 25, -1, false, null},
                {3, 26, -1, false, null},
                {3, 27, -1, false, null},
                {3, 28, -1, false, null},
                {3, 29, -1, false, null},
                {3, 30, -1, false, null},
                {3, 31, -1, false, null},
                {3, 32, -1, false, null},
                {3, 33, -1, false, null},
                {3, 34, -1, false, null},
                {3, 35, -1, false, null},
                {3, 36, -1, false, null},
                {3, 37, -1, false, null},
                {3, 38, -1, false, null},
                {3, 39, -1, false, null},
                {3, 40, -1, false, null},
                {3, 41, -1, false, null},
                {3, 42, -1, false, null},
                {3, 43, -1, false, null},
                {3, 44, -1, false, null},
                {3, 45, -1, false, null},
                {3, 46, -1, false, null},
                {3, 47, -1, false, null},
                {3, 48, -1, false, null},
                {3, 49, -1, false, null},
                {3, 50, -1, false, null},
                {3, 51, -1, false, null},
                {3, 52, -1, false, null},
                {3, 53, -1, false, null},
                {3, 54, -1, false, null},
                {3, 55, -1, false, null},
                {3, 56, -1, false, null},
                {3, 57, -1, false, null},
                {3, 58, -1, false, null},
                {3, 59, -1, false, null},
                {3, 60, -1, false, null},
                {3, 61, -1, false, null},
                {3, 62, -1, false, null},
                {3, 63, -1, false, null},
                {3, 64, -1, false, null},
                {3, 65, -1, false, null},
                {3, 66, -1, false, null},
                {3, 67, -1, false, null},
                {3, 68, -1, false, null},
                {3, 69, -1, false, null},
                {3, 70, -1, false, null},
                {3, 71, -1, false, null},
                {3, 72, -1, false, null},
                {3, 73, -1, false, null},
                {3, 74, -1, false, null},
                {3, 75, -1, false, null},

                /* 4 - 2,6,59,41,16,19,1*/
                {4, 3, -1, false, null},
                {4, 4, -1, false, null},
                {4, 5, -1, false, null},
                {4, 7, -1, false, null},
                {4, 8, -1, false, null},
                {4, 9, -1, false, null},
                {4, 10, -1, false, null},
                {4, 11, -1, false, null},
                {4, 12, -1, false, null},
                {4, 13, -1, false, null},
                {4, 14, -1, false, null},
                {4, 15, -1, false, null},
                {4, 17, -1, false, null},
                {4, 18, -1, false, null},
                {4, 20, -1, false, null},
                {4, 21, -1, false, null},
                {4, 22, -1, false, null},
                {4, 23, -1, false, null},
                {4, 24, -1, false, null},
                {4, 25, -1, false, null},
                {4, 26, -1, false, null},
                {4, 27, -1, false, null},
                {4, 28, -1, false, null},
                {4, 29, -1, false, null},
                {4, 30, -1, false, null},
                {4, 31, -1, false, null},
                {4, 32, -1, false, null},
                {4, 33, -1, false, null},
                {4, 34, -1, false, null},
                {4, 35, -1, false, null},
                {4, 36, -1, false, null},
                {4, 37, -1, false, null},
                {4, 38, -1, false, null},
                {4, 39, -1, false, null},
                {4, 40, -1, false, null},
                {4, 42, -1, false, null},
                {4, 43, -1, false, null},
                {4, 44, -1, false, null},
                {4, 45, -1, false, null},
                {4, 46, -1, false, null},
                {4, 47, -1, false, null},
                {4, 48, -1, false, null},
                {4, 49, -1, false, null},
                {4, 50, -1, false, null},
                {4, 51, -1, false, null},
                {4, 52, -1, false, null},
                {4, 53, -1, false, null},
                {4, 54, -1, false, null},
                {4, 55, -1, false, null},
                {4, 56, -1, false, null},
                {4, 57, -1, false, null},
                {4, 58, -1, false, null},
                {4, 60, -1, false, null},
                {4, 61, -1, false, null},
                {4, 62, -1, false, null},
                {4, 63, -1, false, null},
                {4, 64, -1, false, null},
                {4, 65, -1, false, null},
                {4, 66, -1, false, null},
                {4, 67, -1, false, null},
                {4, 68, -1, false, null},
                {4, 69, -1, false, null},
                {4, 70, -1, false, null},
                {4, 71, -1, false, null},
                {4, 72, -1, false, null},
                {4, 73, -1, false, null},
                {4, 74, -1, false, null},
                {4, 75, -1, false, null},
        });
    }


    private int from;
    private int to;
    private int icon;
    private boolean isValid;
    private Route route;
    private ValidatedRoute routeAndValidity;

    public RoutesTest(int from, int to, int icon, boolean expectedValidity, Route route) {
        this.from = from - 1;
        this.to = to - 1;
        this.icon = icon;
        this.route = route;
        this.isValid = expectedValidity;
    }

    @Before
    public void setUp() {
        routeAndValidity = Routes.getRoute(from, to);
    }

    @Test
    public void routeIsValid() {
        Assert.assertEquals(isValid, routeAndValidity.isValid());
    }

    @Test
    public void isCorrectRoute() {
        Assert.assertEquals(route, routeAndValidity.getRoute());
    }

    @Test
    public void isCorrectRouteType() {
        Assert.assertEquals(icon, routeAndValidity.getRouteType());
    }

    @After
    public void tearDown() {
        routeAndValidity = null;
    }
}
